### ISSUE TITLE
Switch to async implementation

### ISSUE THREAD

**Issue by ngryman** [johno/get-readme#1]
Hi!

I'd like to use this module, but the sync implementation annoys me. Do you think you could switch to an async version using promises? I can make a PR if you want.

Thanks!

**Comment by ngryman** [comment]
Nevermind, I only need the filename anyway. Still, async would be better ❤️

**Comment by johno** [comment]
Sure, happy to accept a PR : )

**Comment by ngryman** [comment]
I released a package because I was in a rush... It's here: https://github.com/ngryman/readme-filename.
I can make you a PR to wrap it and return file contents if you want.

If you prefer keeping your implementation, I would then suggest to only check against valid readme files: https://github.com/github/markup/blob/master/README.md#markups. Currently `readme.1-0.md` would match for example. I can make a PR for this also.

**Comment by johno** [comment]
Epic, yeah. I'd love to leverage your solution to get the filename as it's more elegant. Definitely would accept a PR.

**Comment by johno** [comment]
Published to npm as `get-readme@2.0.0`. Thanks again!

**Comment by vladimyr** [comment]
> Published to npm as `get-readme@2.0.0`. Thanks again!

Hi @johno, sorry for resurrecting pretty old thread but seems like you failed to publish it properly:
https://npmfs.com/package/get-readme/2.0.0/ As you can see `index.js` is not there 😢 

Right now it is basically broken and only way of using it is pulling directly from github so if you don't mind please do a new patch release?

**Comment by johno** [comment]
Thanks for letting me know! It should be good now.

**Comment by vladimyr** [comment]
Yup, all good now. Thanks for fast response! :+1:
